### ISSUE TITLE
Feedback on the latest contributions

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora-docs#22]
- [https://github.com/sora-xor/sora-docs/pull/16](https://github.com/sora-xor/sora-docs/pull/16)
	- Identity
		- The websocket link is not up-to-date.
	- NFT
		- All images are not centered.
		- We need to add more chapter interlinks. For example, in order to start swapping, one will have to add a token to a wallet, which we have mentioned in the warning section at the end. It probably makes sense to include a link to the corresponding heading in this warning box.
	- Nodes connections
		- The pictures are too big.
- [https://github.com/sora-xor/sora-docs/pull/17](https://github.com/sora-xor/sora-docs/pull/17)
	- Account creation
		- I see several pictures added that are not related to the account creation process (e.g., [[https://raw.githubusercontent.com/sora-xor/sora-docs/f3868f45e4f0ea45f65283a4f74ec154d3e4230a/src/.gitbook/assets/image%20(26).png)](https://raw.githubusercontent.com/sora-xor/sora-docs/f3868f45e4f0ea45f65283a4f74ec154d3e4230a/src/.gitbook/assets/image%20(26).png)](https://raw.githubusercontent.com/sora-xor/sora-docs/f3868f45e4f0ea45f65283a4f74ec154d3e4230a/src/.gitbook/assets/image%20(26).png)).
- [https://github.com/sora-xor/sora-docs/pull/19](https://github.com/sora-xor/sora-docs/pull/19)
	- I see a lot of slashes (`/`) added accidentally, I guess.
- Global concerns
	- As guides usually imply linear steps to be followed, it probably makes sense to annotate the steps. For example, [https://github.com/soramitsu/adar/blob/docs/docs/GUIDES.md](https://github.com/soramitsu/adar/blob/docs/docs/GUIDES.md) has the steps highlighted and counted, inspired by [https://developers.google.com/style](https://developers.google.com/style).
	- Currently the project cannot be built from the latest commit (`npm run docs:build`) due to various issues present. It is usually due to incompatibility of Gitbook asset links formatting with Vitepress. For pages migrated earlier, this issue was solved in [https://github.com/sora-xor/sora-docs/commit/7763a36e7735b6bd6600a515eed50620c8660727](https://github.com/sora-xor/sora-docs/commit/7763a36e7735b6bd6600a515eed50620c8660727). As a good practice, I would not merge the pull requests that are not being built. In the future, we will be able to ensure that by having a corresponding I just like Iroha is currently having it implemented ([https://github.com/hyperledger/iroha-2-docs/tree/main/.github/workflows](https://github.com/hyperledger/iroha-2-docs/tree/main/.github/workflows)), but for now, we will have to do it ourselves.
	- We should apply better formatting for all the pages.
	- Maybe it's worth making the figures smaller as they currently cover the entire screen on my PC. The same happens when I'm using my mobile devices.

**Comment by WRRicht3r** [comment]
Hi Boris, thanks for the overall feedback. I think this results from the previous wiki being updated by more than one person, so now the issues are coming to light. No new images were added, aside from those that you did initially or were missing in the articles. I also found the images of the rewards and was confused as to where they came from. 
Regarding image sizes, we need to establish the preferred measurement.
Your global concerns can be addressed today in the call with @outoftardis 
Thanks.

**Comment by outoftardis** [comment]
Thanks for the feedback. I'd add the following to the global concerns:
- check for broken internal links (file names between now and the old wiki have changed, there might be links that are no longer working)
- give images meaningful names

**Comment by WRRicht3r** [comment]
Addressed at weekly meeting.

**Comment by bgodlin** [comment]
@WRRicht3r Is it possible to keep it open until we have it resolved?

**Comment by WRRicht3r** [comment]
What is missing resolution here?

**Comment by outoftardis** [comment]
This has been partially addressed. Here's a quick summary:

## Identity
- [x] The websocket link is not up-to-date. (not updated yet)
## NFT
- [x] Center images
- [x] Add more chapter interlinks (in progress)
## Nodes connections
- [x] Make pictures smaller
## Account creation
- [x] Remove incorrect images, add relevant ones (issue for this: https://github.com/sora-xor/sora-docs/issues/41, in progress)
- [x] Remove slashes (`/`)
## Global concerns
- [x] Annotate the steps
- [x] Better formatting for all the pages
- [x] Make figures smaller (apparently they are still large even after being made smaller, so probably should work on this later)
- [x] Meaningful names for images (in progress)
- [x] Check for broken internal links
